import { Address } from "viem";
import {
  CELO_CHAR_TOKEN_ADDRESS,
  CELO_USDC_TOKEN_ADDRESS,
  MAINNET_UNI_TOKEN_ADDRESS,
  MAINNET_USDC_TOKEN_ADDRESS,
} from "./tokens";

export const CELO_CHAR_USDC_POOL_ADDRESS: Address =
  "0x7f7C4335cCac291DDEdcEf4429A626C442b627ed";

export const ETHEREUM_USDC_UNI_POOL_ADDRESS: Address =
  "0xD0fC8bA7E267f2bc56044A7715A489d851dC6D78";

export const UNISWAP_POOLS_MAP: Record<string, Address> = {
  [`${CELO_USDC_TOKEN_ADDRESS}${CELO_CHAR_TOKEN_ADDRESS}`]:
    CELO_CHAR_USDC_POOL_ADDRESS,
  [`${MAINNET_USDC_TOKEN_ADDRESS}${MAINNET_UNI_TOKEN_ADDRESS}`]:
    ETHEREUM_USDC_UNI_POOL_ADDRESS,
};
